import {
  User,
  Shield,
  Stethoscope,
  Calendar,
  Users,
  BarChart,
  MessageSquare,
  Video,
  Phone,
  Clock,
  CheckCircle,
  XCircle,
  AlertCircle,
  Settings,
  LogOut,
  Loader2,
} from 'lucide-react';

export const Icons = {
  user: User,
  shield: Shield,
  stethoscope: Stethoscope,
  calendar: Calendar,
  users: Users,
  chart: BarChart,
  message: MessageSquare,
  video: Video,
  phone: Phone,
  clock: Clock,
  success: CheckCircle,
  error: XCircle,
  warning: AlertCircle,
  settings: Settings,
  logout: LogOut,
  loading: Loader2,
} as const; 